version: '3.1'

services: 
    ansible-startup:
        build: 
            context: .
        environment: 
            debug: "true"
        env_file: .env
        command: site.yml -e '{"ecs_tasks":["migrate", "collectstatic"], "stack_config":"true", "debug":"true"}'
    
    ansible-update:
        build: 
            context: .
        environment: 
            debug: "true"
        env_file: .env
        command: site.yml -e '{"ecs_tasks":["migrate", "collectstatic"], "image_tag":"reboot87/todobackend:latest", "debug":"true"}'
